/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/
package main

import "fmt"
import "github.com/paolobueno/euler/helpers"

func main() {
	const limit = 4e6
	fib := helpers.Fibonacci()
	sum := 0
	for i := 0; i < limit ; i = fib() {
		if (i % 2) == 0 {
			fmt.Println(i)
			sum += i
		}
	}

	fmt.Printf("Result %d\n", sum)
}